### ISSUE TITLE
Add audit log to webpage next to ad creative

### ISSUE THREAD

**Issue by joshuakoran** [51Degrees/swan-demo-go#8]
Log format can show:

[Common Browser ID]
[Preferences]
[Origin Transaction ID]
[Placement ID]
[Timestamp | Pub ID]
[Timestamp | Processor A ID]
...
Timestamp | Processor n ID]

Processors should be decoded to display the name of the organization signing the origin event

**Comment by jwrosewell** [comment]
This has now been added to the demo.
